import {canonical,fingerprint,sha256,VENDOR_WARNINGS} from '../tools/native/native-admission.mjs';
const buf=x=>Buffer.from(JSON.stringify(x));
export function fixture(){
 const now=Date.parse('2026-09-06T14:00:00Z'),binary={sha256:'b'.repeat(64),bytes:2048,mode:493};
 const main='github.com/zricethezav/gitleaks/v8',module='golang.org/x/crypto',version='v0.56.0',sum='h1:'+'a'.repeat(43)+'=';
 const graph=[{ImportPath:main,Name:'main',Module:{Path:main,Main:true},Imports:[module+'/bcrypt',...Array.from({length:98},(_,i)=>'standard'+i)]},{ImportPath:module+'/bcrypt',Name:'bcrypt',Module:{Path:module,Version:version,Sum:sum}}];for(let i=0;i<98;i++)graph.push({ImportPath:'standard'+i,Name:'standard'+i,Standard:true});
 const packages=[{ID:main,Name:main,Identifier:{PURL:'pkg:golang/'+main},Relationship:'root',AnalyzedBy:'gobinary',DependsOn:[module+'@'+version,'stdlib@v1.26.8']},{ID:module+'@'+version,Name:module,Version:version,Identifier:{PURL:'pkg:golang/'+module+'@'+version},AnalyzedBy:'gobinary'},{ID:'stdlib@v1.26.8',Name:'stdlib',Version:'v1.26.8',Identifier:{PURL:'pkg:golang/stdlib@v1.26.8'},AnalyzedBy:'gobinary'}];
 const finding={VulnerabilityID:'GO-2026-5932',PkgID:module+'@'+version,PkgName:module,InstalledVersion:version,PkgIdentifier:{PURL:'pkg:golang/'+module+'@'+version},Severity:'UNKNOWN',Status:'affected'};
 const report={SchemaVersion:2,Trivy:{Version:'0.74.0+maintenance.1'},ArtifactType:'filesystem',ArtifactName:'/tools',CreatedAt:'2026-09-06T13:59:30Z',Results:[{Target:'gitleaks',Class:'lang-pkgs',Type:'gobinary',Packages:packages,Vulnerabilities:[finding]}]};
 const pcl={binarySha256:binary.sha256,binaryBytes:binary.bytes,compiler:'go1.26.8',mainModule:main,mainPath:main,functions:150,functionNamesSha256:'c'.repeat(64),deprecatedOpenPgpFunctionCount:0,deprecatedOpenPgpFunctionSamples:[],maintainedOpenPgpFunctions:0,method:'debug/elf + debug/gosym Go pclntab decoding; binary not executed',vulnerabilityDisposition:'NOT_YET_ADJUDICATED'};
 const buildInfo=Buffer.from(`/output/gitleaks: go1.26.8\n\tpath\t${main}\n\tmod\t${main}\t(devel)\t\n\tdep\t${module}\t${version}\t${sum}\n\tbuild\tCGO_ENABLED=0\n\tbuild\tGOARCH=amd64\n\tbuild\tGOOS=linux\n\tbuild\t-tags=gore2regex\n`);
 const advisory={id:'GO-2026-5932',affected:[{package:{name:module,ecosystem:'Go'},ranges:[{type:'SEMVER',events:[{introduced:'0'}]}],ecosystem_specific:{imports:['','/armor','/clearsign','/elgamal','/errors','/packet','/s2k'].map(x=>({path:module+'/openpgp'+x}))}}]};
 const input={binary,report:buf(report),stderr:Buffer.from('2026-09-06T13:59:30Z\tWARN\t'+VENDOR_WARNINGS['0.74.0+maintenance.1']+'\n'),graph:Buffer.from(graph.map(JSON.stringify).join('\n')),manifest:buf({files:{'go.mod':'a'.repeat(64),'go.sum':'b'.repeat(64)}}),buildInfo,pclntab:buf(pcl),advisory:buf(advisory)};
 const record={version:1,state:'protected',controlPlaneRepository:'t-scheiber/renovate-config',controlPlaneCommit:'d'.repeat(40),tool:'gitleaks',source:{repository:'gitleaks/gitleaks',commit:'a'.repeat(40),files:2},binary:{sha256:binary.sha256,bytes:binary.bytes},compiler:'go1.26.8',mainModule:main,mainPath:main,graph:{packages:100},buildSettings:{CGO_ENABLED:'0',GOARCH:'amd64',GOOS:'linux','-tags':'gore2regex'},pclntab:{functions:150,maintainedFunctions:0,functionNamesSha256:pcl.functionNamesSha256,inspectorSha256:'d'.repeat(64)},scan:{target:'gitleaks',artifactName:'/tools',scannerVersion:'0.74.0+maintenance.1',scannerSha256:'e'.repeat(64),runtimeConfig:'sha256:'+'f'.repeat(64),packages:3,inventorySha256:fingerprint(packages.toSorted((a,b)=>Buffer.compare(Buffer.from(canonical(a)),Buffer.from(canonical(b))))),findingSha256:fingerprint(finding),vendorWarnings:1,maxAgeMs:3600000},evidence:{}};
 for(const name of ['graph','manifest','buildInfo','pclntab','advisory'])record.evidence[name]=sha256(input[name]);
 input.provenance=buf({version:1,sourceRepository:record.source.repository,sourceCommit:record.source.commit,sourceManifestSha256:record.evidence.manifest,binarySha256:binary.sha256,graphSha256:record.evidence.graph,buildInfoSha256:record.evidence.buildInfo,pclntabSha256:record.evidence.pclntab,inspectorSha256:record.pclntab.inspectorSha256,inspectorSourceSha256:'1'.repeat(64),inspectorFixtureReceiptSha256:'2'.repeat(64),upstreamSourceReceiptSha256:'3'.repeat(64),buildRuntimeReceiptSha256:'4'.repeat(64),compilerArchiveSha256:'5'.repeat(64),dependencyTransitionSha256:'6'.repeat(64),testReceiptSha256:'7'.repeat(64),sourceExecutionNetwork:'none',credentialsPassed:false,inspectedBinaryExecuted:false,testsStatus:'passed'});record.evidence.provenance=sha256(input.provenance);
 input.execution=buf({status:0,platform:'linux/amd64',binarySha256:binary.sha256,scannerSha256:record.scan.scannerSha256,runtimeConfig:record.scan.runtimeConfig,reportSha256:sha256(input.report),stderrSha256:sha256(input.stderr),sourceMounted:false,credentialsPassed:false,network:'none',startedAt:'2026-09-06T13:59:00Z',finishedAt:'2026-09-06T13:59:50Z',database:{sha256:'8'.repeat(64),Version:2,UpdatedAt:'2026-09-06T07:00:00Z',DownloadedAt:'2026-09-06T12:00:00Z',NextUpdate:'2026-09-07T07:00:00Z'}});
 return {input,record,options:{recordSha256:fingerprint(record),now}};
}
function sort(x){return x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.keys(x).sort().map(k=>[k,sort(x[k])])):Array.isArray(x)?x.map(sort):x;}
export function changeJson(f,name,edit,{rebind=false}={}){const value=JSON.parse(f.input[name]);edit(value);f.input[name]=buf(value);if(rebind&&Object.hasOwn(f.record.evidence,name))f.record.evidence[name]=sha256(f.input[name]);if(name==='report'||name==='stderr'){const execution=JSON.parse(f.input.execution);execution[name+'Sha256']=sha256(f.input[name]);f.input.execution=buf(execution);}f.options.recordSha256=fingerprint(f.record);return f;}
